--create sequence hibernate_sequence start 1 increment 1;
--
--create table accounts (
--id long not null,
--account_num varchar(255),
--account_type varchar(255),
--balance float8 not null,
--client_id long,
--primary key (id)
--);
--
--create table clients (
--id long not null,
--first_name varchar(255),
--last_name varchar(255),
--primary key (id)
--);
--
--CREATE TABLE payments_journal (
--payment_id long not null,
--amount float8 not null,
--dest_acc_id long,
--dest_acc_num varchar(255),
--reason varchar(255),
--source_acc_id long,
--src_acc_num varchar(255),
--timestamp varchar(255),
--primary key (payment_id)
--);
--
--afte tabel if exists

